Remove f.ImageDateTime in picsfromfolder result
When using with more than 50000 pictures
 
 for path, filename in picsfromfolder:

cause a 
   ValueError: too many values to unpack

This change fix this. ( f.ImageDateTime in never use in result )